// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP92mQbsy257a2GoouBI56UvG8dF2pQgw',
    appId: '1:595381017668:web:81dab13f4f454e20107011',
    messagingSenderId: '595381017668',
    projectId: 'venenosochatupp',
    authDomain: 'venenosochatupp.firebaseapp.com',
    storageBucket: 'venenosochatupp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-jpXzePXhmY0J5lvaqf9T3tZCKYUf1yA',
    appId: '1:595381017668:android:0d1660708e76d467107011',
    messagingSenderId: '595381017668',
    projectId: 'venenosochatupp',
    storageBucket: 'venenosochatupp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg2v8_nfysxX3OKkuWRE7T6XmIE2mDjuQ',
    appId: '1:595381017668:ios:41f82849aa0c0599107011',
    messagingSenderId: '595381017668',
    projectId: 'venenosochatupp',
    storageBucket: 'venenosochatupp.appspot.com',
    iosClientId: '595381017668-6v7264d5ejk4c148cobcnrf060a3oat8.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatvenenoso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg2v8_nfysxX3OKkuWRE7T6XmIE2mDjuQ',
    appId: '1:595381017668:ios:89f0b1f493227baf107011',
    messagingSenderId: '595381017668',
    projectId: 'venenosochatupp',
    storageBucket: 'venenosochatupp.appspot.com',
    iosClientId: '595381017668-6fljebhtra6ivdtpff9dg2c8cm6q5b50.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatvenenoso.RunnerTests',
  );
}
